name: Full-stack test

on:
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        target: [web, worker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: ${{ matrix.target }}
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.target }}:${{ github.sha }}

  full-stack-test:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up environment
        run: |
          {
            echo "WEBHOOK_URL=http://host.docker.internal:11436"
            echo "SECRET_KEY=$(openssl rand -hex 50)"
            echo "SECURE_SSL_REDIRECT="
          } > .env
      - name: Start the stack
        run: docker compose up --detach
      - name: Install packages
        run: pip install requests
      - name: Run tests
        run: bin/test-full-stack.py
      - name: Get Docker logs
        if: ${{ failure() }}
        run: docker compose logs --timestamps > docker-logs.txt
      - name: Save Docker logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs.txt
          path: docker-logs.txt
